# Quantile delta change configuration

## User configured variables

MAPPING=qm
SCALING=additive
GROUPING=monthly
REFERENCE_QUANTILES=infileq
OUTPUT_GRID=infiles
OUTPUT_UNITS=C
#SSR=--ssr

OBS_DATASET=AGCD
TARGET_VAR=tmin
TARGET_UNITS_ORIG=C
TARGET_START=1990
TARGET_END=2019

MODEL=ACCESS-ESM1-5
EXPERIMENT=ssp370
RUN=r1i1p1f1
MODEL_GRID=gn
NCI_LOC=fs38/publications

HIST_VAR=tasmin
HIST_UNITS_ORIG=K
HIST_VERSION=v20191115
HIST_START=1995
HIST_END=2014

REF_VAR=tasmin
REF_UNITS_ORIG=K
REF_VERSION=v20191115
REF_START=2035
REF_END=2064

# (Hobart)
EXAMPLE_LAT = -42.9
EXAMPLE_LON = 147.3
EXAMPLE_MONTH = 5


## Automatic variables

HIST_FILES_ORIG := $(sort $(wildcard /g/data/${NCI_LOC}/CMIP6/CMIP/*/${MODEL}/historical/${RUN}/day/${HIST_VAR}/${MODEL_GRID}/${HIST_VERSION}/*.nc))
REF_FILES_ORIG := $(sort $(wildcard /g/data/${NCI_LOC}/CMIP6/ScenarioMIP/*/${MODEL}/${EXPERIMENT}/${RUN}/day/${REF_VAR}/${MODEL_GRID}/${REF_VERSION}/*.nc))
TARGET_FILES_ORIG := $(wildcard /g/data/xv83/agcd-csiro/${TARGET_VAR}/daily/*_AGCD-CSIRO_r005_*_daily_space-chunked.zarr)

OUTPUT_HIST_DIR=/g/data/wp00/data/QQ-CMIP6/${MODEL}/historical/${RUN}/day/${HIST_VAR}/${HIST_VERSION}
OUTPUT_REF_DIR=/g/data/wp00/data/QQ-CMIP6/${MODEL}/${EXPERIMENT}/${RUN}/day/${REF_VAR}/${REF_VERSION}
OUTPUT_OBS_DIR=/g/data/wp00/data/${OBS_DATASET}
ifeq (${SSR}, --ssr)
HIST_DATA=${OUTPUT_HIST_DIR}/${HIST_VAR}-ssr_day_${MODEL}_historical_${RUN}_${MODEL_GRID}_${HIST_START}0101-${HIST_END}1231.nc
HIST_UNITS=${OUTPUT_UNITS}
REF_DATA=${OUTPUT_REF_DIR}/${REF_VAR}-ssr_day_${MODEL}_${EXPERIMENT}_${RUN}_${MODEL_GRID}_${REF_START}0101-${REF_END}1231.nc
REF_UNITS=${OUTPUT_UNITS}
REF_FNAME_VAR=${REF_VAR}-ssr
TARGET_DATA=${OUTPUT_OBS_DIR}/${TARGET_VAR}-ssr_${OBS_DATASET}_r005_${TARGET_START}0101-${TARGET_END}1231_daily.nc
TARGET_UNITS=${OUTPUT_UNITS}
TARGET_FNAME_VAR=${TARGET_VAR}-ssr
else
HIST_DATA=${HIST_FILES_ORIG}
HIST_UNITS=${HIST_UNITS_ORIG}
REF_DATA=${REF_FILES_ORIG}
REF_UNITS=${REF_UNITS_ORIG}
REF_FNAME_VAR=${REF_VAR}
TARGET_DATA=${TARGET_FILES_ORIG}
TARGET_UNITS=${TARGET_UNITS_ORIG}
TARGET_FNAME_VAR=${TARGET_VAR}
endif
